version: '3'
  
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres_docker
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_docker
  
  nginx:
    image: nginx:latest
    ports:   
      - "3010:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always