# Generated by Django 4.2.1 on 2023-06-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_imagen_producto_imagen1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_normal',
        ),
    ]
