# Generated by Django 4.2.1 on 2023-06-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_precio_producto_precio_normal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_normal',
            new_name='precio',
        ),
    ]
